#!/bin/bash

PWD="$(cd `dirname $0`; pwd)"

echo "source ${PWD}/all.sh" >> ~/.bashrc

if [ ! -f ~/.gitconfig ]; then
  cp ${PWD}/gitconfig.tpl ~/.gitconfig
fi

if [ ! -f ~/.vimrc ]; then
  cp ${PWD}/vimrc.tpl ~/.vimrc
fi
mkdir -p ~/.vim/ftplugin
mkdir -p ~/.vim/ftdetect
# makefile settings
echo "setlocal noexpandtab" > ~/.vim/ftplugin/make.vim

# iptables highlighting
wget https://raw.githubusercontent.com/eiginn/iptables-vim/master/syntax/iptables.vim -O ~/.vim/ftplugin/iptables.vim
echo "au BufNewFile,BufRead *.rules,*.v4,*.v6 set filetype=iptables" > ~/.vim/ftdetect/iptables.vim
if [ ! -d ~/.ssh ]; then
  mkdir ~/.ssh
  touch ~/.ssh/config
fi
wget http://git-wt-commit.rubyforge.org/git-wtf -O ~/.scripts/git-wtf
chmod +x ~/.scripts/git-wtf

source ~/.bashrc
echo "complete!"
